---
version: 2
plan:
  project-key: FCC
  key: BUILD
  name: freeCodeCamp

stages:
  - Build:
      - Build API-Server
      - Build Static Client

Build API-Server:
  requirements:
     - Node.js 10
  artifacts:
    - name: api-server-bundle.tgz
      location: ${bamboo.working.directory}
      pattern: api-server-bundle.tgz
      required: true
  other:
    clean-working-dir: true
  tasks:
    - script: |
        set -xe
        export PATH="/opt/node-10/bin/:$PATH"

        npm install
        npm run bootstrap
        npm run build:server

        ls -la
        tar czvf api-server-bundle.tgz node_modules config tools utils curriculum api-server
        ls -lah api-server-bundle.tgz

Build Static Client:
  requirements:
     - Node.js 10
     - demanding-builds
  artifacts:
    - name: client-public.tgz
      location: ${bamboo.working.directory}
      pattern: client-public.tgz
      required: true
  other:
    clean-working-dir: true
  tasks:
    - script: |
        set -xe
        export PATH="/opt/node-10/bin/:$PATH"
        cp frontend.env .env

        npm install
        npm run bootstrap
        npm run build:client

        find client/public -type f | wc -l
        du -hs client/public
        tar czvf client-public.tgz client/public
        ls -lah client-public.tgz

---
version: 2
deployment:
  name: freeCodeCamp
  source-plan: FCC-BUILD

release-naming:
  next-version-name: build-${bamboo.buildNumber}

environments:
  - Prod

Prod:
  triggers:
    - stage-success: Build
  tasks:
    - clean
    - artifact-download
    - script: |
        set -ex
        touch .autobamboo.priv
        chmod 600 .autobamboo.priv
        echo $bamboo_deplyoment_secret_autobamboo_privkey_base64 | base64 -d > .autobamboo.priv
    - script: |
        set -ex
        echo "scp'ing client-public.tgz to target"
        scp -oStrictHostKeyChecking=no -i .autobamboo.priv client-public.tgz autobamboo@10.32.1.24:client-public.tgz

        ssh -oStrictHostKeyChecking=no -i .autobamboo.priv autobamboo@10.32.1.24 <<EOF
        set -ex
        tar xvzf client-public.tgz
        sudo chown -R autobamboo:root client
        sudo chmod -R 0755 client
        cd /var/www/freecodecamp/
        rm -rf htdocs_old
        mv htdocs htdocs_old || true
        mv /home/autobamboo/client/public htdocs
        rmdir /home/autobamboo/client
        EOF
    - script: |
        set -ex
        echo "scp'ing api-server-bundle.tgz to target"
        scp -oStrictHostKeyChecking=no -i .autobamboo.priv api-server-bundle.tgz autobamboo@10.32.1.24:api-server-bundle.tgz

        ssh -oStrictHostKeyChecking=no -i .autobamboo.priv autobamboo@10.32.1.24 <<EOF
        set -ex
        rm -rf api-server-bundle
        mkdir api-server-bundle
        cd api-server-bundle
        tar xvzf ../api-server-bundle.tgz

        sudo systemctl stop freecodecamp-api-server.service

        cd /opt/freecodecamp/
        rm -rf api-server-bundle_old
        mv api-server-bundle api-server-bundle_old || true
        mv /home/autobamboo/api-server-bundle api-server-bundle

        sudo systemctl start freecodecamp-api-server.service

        echo "waiting for api-server to start up"
        timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:3000)" != "302" ]]; do echo -n '.'; sleep 5; done' || false
        echo "api-server is up \o/"

        EOF
