---
version: 2
plan:
  project-key: FCC
  key: FCC
  name: freeCodeCamp

stages:
  - Build:
      - Build API-Server
      - Build Static Client

Build API-Server:
  requirements:
     - Node.js 10
  artifacts:
    - name: api-server.tgz
      location: ${bamboo.working.directory}
      pattern: api-server.tgz
      required: true
  tasks:
    - script:
      - set -xe
      - export PATH="/opt/node-10/bin/:$PATH"

      - npm install
      - npm run bootstrap
      - npm run build:server

      - find api-server -type f | wc -l
      - du -hs api-server
      - tar czf api-server.tgz api-server
      - ls -lah api-server.tgz

Build Static Client:
  requirements:
     - Node.js 10
  artifacts:
    - name: client-public.tgz
      location: ${bamboo.working.directory}
      pattern: client-public.tgz
      required: true
  tasks:
    - script:
      - set -xe
      - export PATH="/opt/node-10/bin/:$PATH"
      - cp frontend.env .env

      - npm install
      - npm run bootstrap
      - npm run build:client

      - find client/public -type f | wc -l
      - du -hs client/public
      - tar czf client-public.tgz client/public
      - ls -lah client-public.tgz
