---
version: 2
plan:
  project-key: FCC
  key: BUILD
  name: freeCodeCamp

stages:
  - Build:
      - Build API-Server
      - Build Static Client

Build API-Server:
  requirements:
     - Node.js 10
  artifacts:
    - name: api-server.tgz
      location: ${bamboo.working.directory}
      pattern: api-server.tgz
      required: true
  other:
    clean-working-dir: true
  tasks:
    - script: |
        set -xe
        export PATH="/opt/node-10/bin/:$PATH"

        npm install
        npm run bootstrap
        npm run build:server

        find api-server -type f | wc -l
        du -hs api-server
        tar czf api-server.tgz api-server
        ls -lah api-server.tgz

Build Static Client:
  requirements:
     - Node.js 10
     - demanding-builds
  artifacts:
    - name: client-public.tgz
      location: ${bamboo.working.directory}
      pattern: client-public.tgz
      required: true
  other:
    clean-working-dir: true
  tasks:
    - script: |
        set -xe
        export PATH="/opt/node-10/bin/:$PATH"
        cp frontend.env .env

        npm install
        npm run bootstrap
        npm run build:client

        find client/public -type f | wc -l
        du -hs client/public
        tar czf client-public.tgz client/public
        ls -lah client-public.tgz

---
version: 2
deployment:
  name: freeCodeCamp
  source-plan: FCC-BUILD

release-naming:
  next-version-name: build-${bamboo.buildNumber}

environments:
  - Prod

Prod:
  triggers:
    - stage-success: Build
  tasks:
    - clean
    - artifact-download
    - script: |
        set -ex
        touch .autobamboo.priv
        chmod 600 .autobamboo.priv
        echo $bamboo_deplyoment_secret_autobamboo_privkey_base64 | base64 -d > .autobamboo.priv

        echo "scp'ing bundle to target"
        scp -oStrictHostKeyChecking=no -i .autobamboo.priv client-public.tgz autobamboo@10.32.1.24:client-public.tgz

        ssh -oStrictHostKeyChecking=no -i .autobamboo.priv autobamboo@10.32.1.24 <<EOF
        set -ex
        tar xvzf client-public.tgz
        cd /var/www/freecodecamp/
        rm -rf htdocs_old
        mv htdocs htdocs_old
        mv /home/autobamboo/client/public htdocs
        EOF
